steps:

  - id: "Rodando app test"
    name: 'gcr.io/cloud-builders/go'
    env: ['PROJECT_ROOT=github.com/aguinelo/desafiocd']
    args: ['test', './app/src']
  
  - id: "Image Build from Dockerfile.prod"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafiocd:$SHORT_SHA', '-f', './app/Dockerfile.prod', './app']

  - id: "Pushing Image"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/desafiocd:$SHORT_SHA']

  - id: "Adjusting deployment file - k8s"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/desafiocd:$SHORT_SHA#g' .k8s/deployment.yml .k8s/deployment-new.yml;
        cat .k8s/deployment-new.yml;
