steps:

- id: "Rodando app test"
  name: 'gcr.io/cloud-builders/go'
  env: ['PROJECT_ROOT=github.com/aguinelo/desafiocd']
  args: ['test', './app/src']

- id: "Image Build"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafiocd:latest', './app']
  
images:

  - 'gcr.io/$PROJECT_ID/desafiocd:latest'